name: Simple Deployment 
on: 
    push:
        branches: 
            - master
jobs:
    depoloyment_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout the repo
          uses: actions/checkout@v4

        - name: Build the image
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/facetest:1.0.0 .

        - name: Login to Docker Hub
          run: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Push the image to Docker Hub
          run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/facetest:1.0.0

        - name: Access the Helm repository
          run: |
            
            git config --global user.email "theoafactor@gmail.com"
            git config --global user.name "Olu Adeyemo"
            git remote set-url origin https://${{ secrets.REPO_TOKEN }}@github.com/theoafactor/facetest.com_helm.git
            
            git clone https://github.com/theoafactor/facetest.com_helm.git  
            cd facetest.com_helm/facetest/templates

            sed -i s"/facetest:1.0.0/facetest:2.0.0/" deployment.yaml
            cat deployment.yaml
            git add -A
            git commit -m "Updated Helm template file for deployment"

            git push origin master



            

        